<?php

namespace App\Filament\Resources\Loans\Actions;

use App\Enums\LoanStatus;
use App\Models\Loan;
use Filament\Actions\Action;
use Filament\Notifications\Notification;

class ApproveLoanAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->label('Approve Loan')
            ->color('success')
            ->icon('heroicon-o-check-circle')
            ->requiresConfirmation()
            ->modalHeading('Approve Loan')
            ->modalDescription('Are you sure you want to approve this loan? This will move it to pending disbursement.')
            ->modalSubmitActionLabel('Yes, Approve Loan')
            ->visible(fn (?Loan $loan) => $loan && $loan->status === LoanStatus::PENDING_APPROVAL)
            ->action(function (Loan $loan) {
                $userName = auth()->user()->name ?? 'System';
                $loan->update([
                    'status' => LoanStatus::PENDING_DISBURSEMENT,
                    'remarks' => "Loan Approved By {$userName} on " . now()->format('Y-m-d H:i:s'),
                ]);

                Notification::make()
                    ->title('Loan Approved')
                    ->body('Loan has been approved successfully.')
                    ->success()
                    ->send();
            });
    }
}
