<?php

namespace App\Filament\Resources\Loans\Actions;

use App\Enums\LoanStatus;
use App\Models\Loan;
use Filament\Actions\Action;
use Filament\Notifications\Notification;

class ClearLoanAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->label('Clear Loan')
            ->color('yellow')
            ->icon('hugeicons-clean')
            ->requiresConfirmation()
            ->modalHeading('Clear Loan')
            ->modalDescription('Are you sure you want to clear this loan? This will move it to pending confirmation.')
            ->modalSubmitActionLabel('Yes, Clear Loan')
            ->visible(fn (?Loan $loan) => $loan && in_array($loan->status, [LoanStatus::DISBURSED, LoanStatus::OVERDUE, LoanStatus::PAST_OVERDUE, LoanStatus::WRITTEN_OFF]))
            ->action(function (Loan $loan){
                $userName = auth()->user()->name ?? 'System';
                $loan->update([
                    'status' => LoanStatus::CLEARED,
                    'remarks' => $loan->remarks . "<br>Loan Cleared By {$userName} on " . now()->format('Y-m-d H:i:s'),
                ]);

                Notification::make()
                    ->title('Loan Cleared')
                    ->body('Loan has been cleared successfully.')
                    ->success()
                    ->send();
            });
    }
}
