<?php

namespace App\Filament\Resources\Loans\Actions;

use App\Enums\LoanStatus;
use App\Models\Loan;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Illuminate\Support\Facades\DB;

class ConfirmLoanAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->label('Confirm Loan')
            ->color('success')
            ->icon('heroicon-o-check-circle')
            ->requiresConfirmation()
            ->modalHeading('Confirm Loan')
            ->modalDescription('Are you sure you want to confirm this loan? This will move it to pending approval.')
            ->modalSubmitActionLabel('Yes, Confirm Loan')
            ->visible(fn (?Loan $loan) => $loan && $loan->status === LoanStatus::PENDING_CONFIRMATION)
            ->action(function (Loan $loan) {
                $userName = auth()->user()->name ?? 'System';
                $loan->update([
                    'status' => LoanStatus::PENDING_APPROVAL,
                    'remarks' => $loan->remarks . "<br>Loan Confirmed By {$userName} on ".now()->format('Y-m-d H:i:s')
                ]);
                Notification::make()
                    ->title('Loan Confirmed')
                    ->body('Loan has been confirmed successfully.')
                    ->success()
                    ->send();
            });
    }
}
