<?php

namespace App\Filament\Resources\Loans\Actions;

use App\Enums\LoanStatus;
use App\Models\Loan;
use Filament\Actions\Action;
use Filament\Notifications\Notification;

class DisburseLoanAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->label('Disburse Loan')
            ->color('success')
            ->icon('hugeicons-new-releases')
            ->requiresConfirmation()
            ->modalHeading('Disburse Loan')
            ->modalDescription('Are you sure you want to disburse this loan? This will move it to disbursed.')
            ->modalSubmitActionLabel('Yes, Disburse Loan')
            ->visible(fn (?Loan $loan) => $loan && $loan->status === LoanStatus::PENDING_DISBURSEMENT)
            ->action(function (Loan $loan){
                $userName = auth()->user()->name ?? 'System';
                $loan->update([
                    'status' => LoanStatus::DISBURSED,
                    'remarks' => "Loan Disbursed By {$userName} on " . now()->format('Y-m-d H:i:s'),
                ]);
                Notification::make()
                    ->title('Loan Disbursed')
                    ->body('Loan has been disbursed successfully.')
                    ->success()
                    ->send();
            });
    }
}
