<?php

namespace App\Filament\Resources\Loans\Actions;

use App\Enums\LoanStatus;
use App\Models\Loan;
use Filament\Actions\Action;
use Filament\Notifications\Notification;

class MarkDisbursedAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->label('Mark as Disbursed')
            ->color('warning')
            ->icon('hugeicons-new-releases')
            ->requiresConfirmation()
            ->modalHeading('Mark Loan as Disbursed')
            ->modalDescription('Are you sure you want to mark this loan as disbursed? This will move it to disbursed.')
            ->modalSubmitActionLabel('Yes, Mark as Disbursed')
            ->visible(fn (?Loan $loan) => $loan && in_array($loan->status, [
                LoanStatus::PENDING_DISBURSEMENT,
                LoanStatus::PENDING_APPROVAL,
                LoanStatus::PENDING_CONFIRMATION,
                LoanStatus::OVERDUE,
                LoanStatus::PAST_OVERDUE,
                LoanStatus::WRITTEN_OFF,
                LoanStatus::CLEARED
            ]))
            ->action(function (Loan $loan){
                $userName = auth()->user()->name ?? 'System';
                $loan->update([
                    'status' => LoanStatus::DISBURSED,
                    'remarks' => $loan->remarks . "<br>Loan Marked as Disbursed By {$userName} on " . now()->format('Y-m-d H:i:s'),
                ]);
                Notification::make()
                    ->title('Marked as Disbursed')
                    ->body('Loan has been marked as disbursed successfully.')
                    ->success()
                    ->send();
            });
    }
}
