<?php

namespace App\Filament\Resources\Loans\Actions;

use App\Enums\LoanStatus;
use App\Models\Loan;
use App\Models\Refinance;
use Filament\Actions\Action;

class RefinanceLoanAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->label('Refinance Loan')
            ->color('purple')
            ->icon('heroicon-o-wrench')
            ->schema([
                //TODO: Add Refinance Form
            ])
            ->requiresConfirmation()
            ->visible(fn (?Loan $loan) => $loan && in_array($loan->status, [LoanStatus::DISBURSED, LoanStatus::OVERDUE]) && $loan->isEligibleForRefinance())
            ->action(function (Loan $loan) {
                //TODO: 1. Check if Customer is eligible for refinance
                //TODO: 2. Clear Old Loan and add remark 'Loan cleared due to refinance by {loggedIn User} on {timestamp}'
                //TODO: 3. Create a new loan with new loan amount, with remark 'Loan refinance of {refinance amount} created by {loggedIn User} on {timestamp}<br>Previous Principal: {previous principal}, New Loan: {new loan amount}, Interest: {}'
                //TODO: 4. Create the refinance

            });
    }
}
