<?php

namespace App\Filament\Resources\Loans\Actions;

use App\Enums\LoanStatus;
use App\Filament\Resources\Loans\LoanResource;
use App\Filament\Resources\Refinances\Schemas\RefinanceForm;
use App\Models\Loan;
use App\Models\Refinance;
use App\Services\LoanService;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Schemas\Schema;
use Illuminate\Support\Facades\Log;

class RefinanceLoanAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->label('Refinance Loan')
            ->color('purple')
            ->icon('hugeicons-move-top')
            ->schema(fn (Loan $loan) => RefinanceForm::getFormSchema($loan))
            ->requiresConfirmation()
            ->modalHeading('Refinance Loan')
            ->modalDescription('Please confirm the refinance amount and details.')
            ->modalIcon('hugeicons-move-top')
            ->modalSubmitActionLabel('Refinance Loan')
            ->visible(fn (?Loan $loan) => $loan && in_array($loan->status, [LoanStatus::DISBURSED, LoanStatus::OVERDUE]) && $loan->isEligibleForRefinance())
            ->action(function (Loan $loan, array $data) {
                try {
                    $loanService = app(LoanService::class);
                    $result = $loanService->processRefinance($loan, $data['amount'], auth()->user());

                    if ($result['success']) {
                        Notification::make()
                            ->title('Loan Refinanced Successfully')
                            ->body('Loan has been refinanced successfully. Old Loan marked cleared.')
                            ->success()
                            ->send();

                        // Redirect to the new loan view page
                        $this->redirect(LoanResource::getUrl('view', ['record' => $result['new_loan']->id]));
                    }
                } catch (\Exception $e) {
                    Log::error("Error Creating Refinance: {$e->getMessage()}");
                    Notification::make()
                        ->title('Loan Refinancing Failed')
                        ->body("Error: {$e->getMessage()}")
                        ->danger()
                        ->send();
                }
            });
    }
}
