<?php

namespace App\Filament\Resources\Loans\Actions;

use App\Enums\LoanStatus;
use App\Models\Loan;
use Filament\Actions\Action;
use Illuminate\Support\Facades\DB;
use Filament\Notifications\Notification;

class VerifyLoanAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this
            ->label('Verify Loan')
            ->color('blue')
            ->icon('heroicon-o-check-circle')
            ->requiresConfirmation()
            ->modalHeading('Verify Loan')
            ->modalDescription('Are you sure you want to verify this loan? This will move it to pending confirmation.')
            ->modalSubmitActionLabel('Yes, Verify Loan')
            ->visible(fn (?Loan $loan) => $loan && $loan->status === LoanStatus::PENDING_VERIFICATION)
            ->action(function (Loan $loan) {
                $userName = auth()->user()->name ?? 'System';
                $loan->update([
                    'status' => LoanStatus::PENDING_CONFIRMATION,
                    'remarks' => $loan->remarks . "<br>Loan Verified By {$userName} on " . now()->format('Y-m-d H:i:s'),
                ]);
                Notification::make()
                    ->title('Loan Verified Successfully')
                    ->body("Loan #{$loan->id} has been verified and is now pending confirmation.")
                    ->success()
                    ->send();
            });
    }
}
